version: '2'

services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"

  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_CREATE_TOPICS: "quotes_topic:1:1"
    depends_on:
      - zookeeper

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: quotes_db
      MYSQL_USER: root
      MYSQL_PASSWORD: password 
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  scraper_orchestrator:
    build: ./scraper_orchestrator
    depends_on:
      - kafka

  consumer_service:
    build: ./consumer_service
    depends_on:
      - kafka
      - mysql

  frontend:
    build: ./frontend
    ports:
      - "5000:5000"
    depends_on:
      - mysql

volumes:
  mysql_data:
